name: New Selenium Test Workflow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-selenium-tests-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        chrome-version: [latest, 129]
        selenium-version: [4.26.0]
        java-version: [17]

    steps:
    - name: Call Reusable Setup
      uses: ./.github/workflows/reusable-setup.yml@main  # Specify branch if needed
      with:
        os: ubuntu-latest
        browser: ${{ matrix.browser }}
        chrome-version: ${{ matrix.chrome-version }}
        java-version: ${{ matrix.java-version }}

    - name: Set Selenium version
      run: echo "SELENIUM_VERSION=${{ matrix.selenium-version }}" >> $GITHUB_ENV

    - name: Run Selenium tests
      run: |
        cd selenium-test-project
        echo "Running tests in headless mode on Linux..."
        ./gradlew clean test -Dheadless=true -DseleniumVersion=${{ env.SELENIUM_VERSION }}

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-ubuntu-${{ github.run_id }}-${{ matrix.browser }}-${{ matrix.java-version }}-${{ matrix.headless }}
        path: build/test-results/reports
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: true

  run-selenium-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome]
        chrome-version: [latest, 129]
        selenium-version: [4.26.0]
        java-version: [17]

    steps:
    - name: Call Reusable Setup
      uses: ./.github/workflows/reusable-setup.yml@main  # Specify branch if needed
      with:
        os: windows-latest
        browser: ${{ matrix.browser }}
        chrome-version: ${{ matrix.chrome-version }}
        java-version: ${{ matrix.java-version }}

    - name: Set Selenium version
      run: echo "SELENIUM_VERSION=${{ matrix.selenium-version }}" >> $GITHUB_ENV

    - name: Run Selenium tests
      shell: cmd
      run: |
        cd selenium-test-project
        echo "Running tests in normal mode on Windows..."
        gradlew.bat clean test -Dheadless=false -DseleniumVersion=${{ env.SELENIUM_VERSION }}

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-windows-${{ github.run_id }}-${{ matrix.browser }}-${{ matrix.java-version }}-${{ matrix.headless }}
        path: build/test-results/reports
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: true
