name: Reusable Setup

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      browser:
        required: true
        type: string
      chrome-version:
        required: false
        type: string
      firefox-version:
        required: false
        type: string
      java-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Install Google Chrome
      if: ${{ inputs.browser == 'chrome' }}
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ inputs.chrome-version }}
        install-chromedriver: true

    - name: Install Firefox
      if: ${{ inputs.browser == 'firefox' }}
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ inputs.firefox-version }}

    - name: Set permissions for gradlew
      run: chmod +x selenium-test-project/gradlew
